const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@TruongNBP";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "TruongNBP";
const forgetPass = "Forget Password";
const login = "Login";
const signup = "Sign Up";
const createNewAccount = "or, create New Account";
const loginWith = "Login with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account ? ";

const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";

const searchanything = "Search anything...",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "Tshirts",
    girlsDress = "Girls Dress",
    featuredProducts = "Featured Products",
    featuredCategories = "Featured Categories";
